# Generated by Django 5.2.3 on 2026-07-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_telegrambroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'П’ятниця'), (5, 'Субота'), (6, 'Неділя')], verbose_name='день тижня'),
        ),
    ]
