# Generated by Django 5.2.3 on 2026-08-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0017_alter_scheduleentry_weekday"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="дата заняття")),
                ("title", models.CharField(blank=True, max_length=180, verbose_name="тема або назва заняття")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="створено")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_sessions", to="learning.course", verbose_name="курс")),
            ],
            options={"verbose_name": "заняття в журналі відвідуваності", "verbose_name_plural": "журнал відвідуваності", "ordering": ["-date", "course__title"]},
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("present", "Був/була"), ("absent", "Відсутній/відсутня"), ("late", "Запізнився/запізнилась"), ("excused", "Поважна причина")], default="present", max_length=20, verbose_name="статус")),
                ("note", models.CharField(blank=True, max_length=180, verbose_name="примітка")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="records", to="learning.attendancesession", verbose_name="заняття")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to=settings.AUTH_USER_MODEL, verbose_name="учень")),
            ],
            options={"verbose_name": "відмітка відвідуваності", "verbose_name_plural": "відмітки відвідуваності", "ordering": ["student__first_name", "student__last_name", "student__username"]},
        ),
        migrations.AddConstraint(model_name="attendancesession", constraint=models.UniqueConstraint(fields=("course", "date"), name="unique_attendance_course_date")),
        migrations.AddConstraint(model_name="attendancerecord", constraint=models.UniqueConstraint(fields=("session", "student"), name="unique_attendance_session_student")),
    ]
