# Generated by Django 5.2.3 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0018_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=255, verbose_name="правильна текстова відповідь"),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(choices=[("choice", "Обрати правильну відповідь"), ("text", "Вписати відповідь / заповнити пропуск")], default="choice", max_length=16, verbose_name="тип питання"),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="text_answer",
            field=models.CharField(blank=True, max_length=255, verbose_name="текстова відповідь учня"),
        ),
    ]
