# Generated by Django 5.2.3 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0019_quiz_question_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="drag_options",
            field=models.TextField(blank=True, help_text="Кожен варіант з нового рядка", verbose_name="варіанти для перетягування"),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="quizzes/images/", verbose_name="зображення до питання"),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="посилання на зображення"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(choices=[("choice", "Обрати правильну відповідь"), ("text", "Вписати відповідь / заповнити пропуск"), ("drag", "Перетягнути відповідь у пропуск")], default="choice", max_length=16, verbose_name="тип питання"),
        ),
    ]
